import test from 'node:test';import assert from 'node:assert/strict';
import {Puzzle,sanitize} from '../src/simulation.ts';import {LEVELS,key,type Piece} from '../src/levels.ts';
function solution(g:Puzzle){for(const c of g.config.solution)assert.ok(g.place(c.x,c.z,c.kind as Piece,c.rot));}
function run(g:Puzzle){assert.ok(g.start());let waiting=false,jumps=0;for(let i=0;i<60*45&&g.phase==='running';i++){g.tick(1/60);waiting ||=g.balls.some(b=>b.state==='waiting');jumps+=g.events.filter(e=>e.type==='bounce').length;g.events=[];}return {waiting,jumps};}
test('all nine authored layouts solve with finite stock and three stars',()=>{const results=[];for(let i=0;i<9;i++){const g=new Puzzle(i);solution(g);run(g);results.push({level:i+1,phase:g.phase,time:+g.time.toFixed(2),caught:g.collected});assert.equal(g.phase,'won',JSON.stringify(g.snapshot()));assert.equal(g.stars,3);assert.equal(g.collected,g.total);}console.log('Solutions:',JSON.stringify(results));});
test('fixed cells, stock and running edits are protected',()=>{const g=new Puzzle(0);assert.equal(g.place(0,1,'straight',0),false);assert.equal(g.erase(0,1),false);assert.equal(g.place(1,0,'spring',0),false);for(const x of [0,1,2])assert.ok(g.place(x,5,'straight',0));assert.equal(g.place(3,5,'straight',0),false);assert.ok(g.erase(2,5));assert.ok(g.place(3,5,'straight',0));g.start();assert.equal(g.rotate(3,5),false);assert.equal(g.place(2,4,'bend',0),false);});
test('rotation, undo and retry retain the editable layout',()=>{const g=new Puzzle(0);g.place(1,1,'straight',0);assert.ok(g.rotate(1,1));assert.equal(g.board.get('1,1')?.rot,1);assert.ok(g.undo());assert.equal(g.board.get('1,1')?.rot,0);g.start();g.pause();assert.ok(g.rotate(1,1));assert.equal(g.phase,'build');assert.equal(g.balls.length,0);assert.equal(g.board.get('1,1')?.rot,1);});
test('an open end fails and the layout remains available to fix',()=>{const g=new Puzzle(0);g.place(1,1,'straight',1);run(g);assert.equal(g.phase,'failed');assert.match(g.message,/left the track/);g.retry();assert.equal(g.board.get('1,1')?.kind,'straight');assert.equal(g.phase,'build');});
test('wrong cup and wrong rail entry fail clearly',()=>{const g=new Puzzle(0);solution(g);g.board.get('3,3')!.color='blue';run(g);assert.equal(g.phase,'failed');assert.match(g.message,/Wrong cup/);const wrong=new Puzzle(0);wrong.place(1,1,'straight',0);run(wrong);assert.match(wrong.message,/openings/);});
test('springs jump across exactly one gap and land on the intended rail',()=>{const g=new Puzzle(2);solution(g);const {jumps}=run(g);assert.equal(g.phase,'won');assert.equal(jumps,2);assert.equal(g.board.get(key(1,3))?.kind,'hole');});
test('one marble waits while another opens its gate',()=>{const g=new Puzzle(7);solution(g);const {waiting}=run(g);assert.ok(waiting);assert.ok(g.gates.has('mint'));assert.equal(g.collected,2);assert.equal(g.phase,'won');});
test('two seesaws route three colors to three different cups',()=>{const g=new Puzzle(8);solution(g);run(g);assert.equal(g.flips.get('2,2'),3);assert.equal(g.flips.get('1,2'),2);assert.deepEqual(new Set(g.balls.map(b=>b.cell)),new Set(['0,1','1,5','4,5']));assert.equal(g.phase,'won');});
test('pause freezes motion and resume continues the same run',()=>{const g=new Puzzle(0);solution(g);g.start();for(let i=0;i<50;i++)g.tick(1/60);g.pause();const before=JSON.stringify(g.snapshot());for(let i=0;i<120;i++)g.tick(1/60);assert.equal(JSON.stringify(g.snapshot()),before);g.start();assert.equal(g.runs,1);for(let i=0;i<600&&g.phase==='running';i++)g.tick(1/60);assert.equal(g.phase,'won');});
test('hints reduce stars without blocking completion and saves are clamped',()=>{const g=new Puzzle(0);assert.ok(g.hint().text);solution(g);run(g);assert.equal(g.stars,2);const p=sanitize({unlocked:99,stars:[100,-5,2],theme:50,skin:8});assert.equal(p.unlocked,8);assert.equal(p.stars[0],3);assert.equal(p.stars[1],0);assert.equal(p.theme,0);assert.equal(p.skin,0);});
