export type Color='coral'|'blue'|'gold';
export type Piece='straight'|'bend'|'spring'|'magnet'|'seesaw';
export type Kind=Piece|'source'|'cup'|'switch'|'gate'|'hole';
export interface Tile{kind:Kind;rot:number;fixed?:boolean;color?:Color;colors?:Color[];key?:string;shape?:'bend';}
export interface Cell extends Tile{x:number;z:number}
export interface Level{name:string;subtitle:string;brief:string;fixed:Cell[];solution:Cell[];stock:Partial<Record<Piece,number>>;par:number;theme:number;lesson:string}
export const COLORS:Record<Color,number>={coral:0xec806b,blue:0x5aabc9,gold:0xf0c45f};
export const PIECES:Record<Piece,{name:string;unlock:number;hint:string}>={straight:{name:'Straight',unlock:0,hint:'Connect two opposite sides.'},bend:{name:'Bend',unlock:0,hint:'Turn a marble through 90 degrees.'},spring:{name:'Spring',unlock:2,hint:'Jump over one square. The arrow points to the landing.'},magnet:{name:'Magnet',unlock:5,hint:'Catch a marble and guide it along the arrow.'},seesaw:{name:'Seesaw',unlock:6,hint:'First marble turns right, next turns left. Then repeat.'}};
const p=(x:number,z:number,kind:Kind,rot=0,rest:Partial<Tile>={}):Cell=>({x,z,kind,rot,...rest});
const src=(x:number,z:number,rot:number,colors:Color[])=>p(x,z,'source',rot,{colors});
const cup=(x:number,z:number,color:Color)=>p(x,z,'cup',0,{color});
const hole=(x:number,z:number)=>p(x,z,'hole');
export const LEVELS:Level[]=[
 {name:'A Little Turn',subtitle:'THE FIRST LITTLE ROLL',brief:'Join the coral marble to its matching cup. Two bends should do it.',theme:0,par:4,stock:{straight:3,bend:3},fixed:[src(0,1,1,['coral']),cup(3,3,'coral'),hole(0,3),hole(3,0),hole(4,2),hole(5,4)],solution:[p(1,1,'straight',1),p(2,1,'bend',2),p(2,2,'straight',0),p(2,3,'bend',0)],lesson:'A bend joins its two marked openings. Tap a placed piece again to rotate it.'},
 {name:'The Scenic Route',subtitle:'TAKE THE LONG WAY HOME',brief:'A few twists, a little climb. Keep every opening connected.',theme:1,par:7,stock:{straight:5,bend:4},fixed:[src(0,4,1,['blue']),cup(4,0,'blue'),hole(2,0),hole(3,4),hole(1,2),hole(5,2)],solution:[p(1,4,'straight',1),p(2,4,'bend',3),p(2,3,'straight',0),p(2,2,'bend',1),p(3,2,'straight',1),p(4,2,'bend',3),p(4,1,'straight',0)],lesson:'Follow the openings with your finger: start, straight, bend, and on to the blue cup.'},
 {name:'Hop, Skip, Roll',subtitle:'MEET YOUR FIRST SPRING',brief:'The dark gaps are too wide to roll across. Give your marble a little lift.',theme:2,par:6,stock:{straight:3,bend:3,spring:2},fixed:[src(1,5,0,['coral']),cup(3,4,'coral'),hole(1,3),hole(3,3),hole(2,4),hole(2,5),hole(4,2)],solution:[p(1,4,'spring',0),p(1,2,'straight',0),p(1,1,'bend',1),p(2,1,'straight',1),p(3,1,'bend',2),p(3,2,'spring',2)],lesson:'A spring skips exactly one square and lands two squares ahead. Point its arrow along the jump.'},
 {name:'Better Together',subtitle:'TWO COLORS. TWO DESTINATIONS.',brief:'Build two little journeys. Every marble needs its own matching cup.',theme:3,par:8,stock:{straight:5,bend:5},fixed:[src(0,1,1,['coral']),cup(3,3,'coral'),src(5,4,3,['blue']),cup(3,1,'blue'),hole(1,3),hole(2,4),hole(5,1)],solution:[p(1,1,'straight',1),p(2,1,'bend',2),p(2,2,'straight',0),p(2,3,'bend',0),p(4,4,'bend',0),p(4,3,'straight',0),p(4,2,'straight',0),p(4,1,'bend',2)],lesson:'Different colors can share rails, but a cup only accepts its own color.'},
 {name:'After You',subtitle:'A LITTLE FAVOR GOES A LONG WAY',brief:'Let coral press the orange switch. Blue will wait at the matching gate.',theme:0,par:8,stock:{straight:6,bend:3},fixed:[src(0,0,2,['coral']),p(2,1,'switch',1,{key:'orange'}),cup(4,3,'coral'),src(0,4,1,['blue']),p(2,4,'gate',1,{key:'orange'}),cup(5,4,'blue'),hole(2,2),hole(1,3),hole(4,1)],solution:[p(0,1,'bend',0),p(1,1,'straight',1),p(3,1,'bend',2),p(3,2,'straight',0),p(3,3,'bend',0),p(1,4,'straight',1),p(3,4,'straight',1),p(4,4,'straight',1)],lesson:'Gates stay closed until a marble presses the matching switch. Waiting marbles start rolling again automatically.'},
 {name:'Magnetic Personality',subtitle:'A GENTLE PULL IN THE RIGHT DIRECTION',brief:'Use the purple magnets to steer around the missing squares.',theme:4,par:7,stock:{straight:3,magnet:4},fixed:[src(0,3,1,['blue']),cup(4,3,'blue'),hole(2,3),hole(2,4),hole(1,0),hole(3,0),hole(3,4)],solution:[p(1,3,'magnet',0),p(1,2,'straight',0),p(1,1,'magnet',1),p(2,1,'straight',1),p(3,1,'magnet',2),p(3,2,'straight',0),p(3,3,'magnet',1)],lesson:'A magnet accepts a marble from any side except its arrow, then redirects it along that arrow.'},
 {name:'A Little Balance',subtitle:'ONE FOR YOU. ONE FOR ME.',brief:'One start, two marbles. A seesaw shares them between the two cups.',theme:1,par:6,stock:{straight:4,bend:3,seesaw:1},fixed:[src(2,0,2,['coral','blue']),cup(1,4,'coral'),cup(3,4,'blue'),hole(2,3),hole(0,2),hole(4,2)],solution:[p(2,1,'straight',0),p(2,2,'seesaw',2),p(1,2,'bend',1),p(1,3,'straight',0),p(3,2,'bend',2),p(3,3,'straight',0)],lesson:'Face the seesaw arrow along the incoming direction. The first marble turns right, the second left.'},
 {name:'You Go, I Go',subtitle:'TEAMWORK MAKES THE MARBLES ROLL',brief:'Coral waits. Blue opens the gate. Then both get a spring-powered finish.',theme:3,par:6,stock:{straight:2,bend:3,spring:2,seesaw:1},fixed:[src(2,0,2,['coral','blue']),p(1,2,'gate',1,{key:'mint'}),p(3,2,'switch',1,{key:'mint'}),cup(0,5,'coral'),cup(4,5,'blue'),hole(0,4),hole(4,4),hole(2,3),hole(1,4)],solution:[p(2,1,'straight',0),p(2,2,'seesaw',2),p(0,2,'bend',1),p(0,3,'spring',2),p(4,2,'bend',2),p(4,3,'spring',2)],lesson:'The blue marble must reach the mint switch while coral is waiting. Keep the two exit paths separate.'},
 {name:'The Grand Parade',subtitle:'THREE MARBLES. ONE HAPPY MACHINE.',brief:'Two seesaws, a gate, two jumps. Give every color its moment.',theme:5,par:6,stock:{straight:2,spring:2,magnet:2,seesaw:2},fixed:[src(2,0,2,['coral','blue','gold']),p(1,1,'switch',2,{key:'orange',shape:'bend'}),cup(0,1,'coral'),p(3,2,'gate',1,{key:'orange'}),cup(1,5,'gold'),cup(4,5,'blue'),hole(1,4),hole(4,4),hole(2,3),hole(3,4)],solution:[p(2,1,'straight',0),p(2,2,'seesaw',2),p(1,2,'seesaw',3),p(1,3,'spring',2),p(4,2,'magnet',2),p(4,3,'spring',2)],lesson:'The left seesaw sends its first visitor north and its next south. Coral goes first, gold follows later.'},
];
export const dirs=[{x:0,z:-1},{x:1,z:0},{x:0,z:1},{x:-1,z:0}];
export const key=(x:number,z:number)=>`${x},${z}`;
export const cellName=(x:number,z:number)=>`${'ABCDEF'[x]}${z+1}`;
export function openings(t:Tile){return t.kind==='bend'||t.shape==='bend'?[t.rot,(t.rot+1)%4]:[t.rot,(t.rot+2)%4];}
