import './style.css';
import {LEVELS,PIECES,cellName,type Piece,type Tile} from './levels';
import {Puzzle,sanitize,freshProfile,type Profile} from './simulation';
import {MarbleWorld} from './world';import {Sound} from './audio';
const $=<T extends HTMLElement=HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const SAVE='marble-parade-save-v1';let profile:Profile=freshProfile();try{profile=sanitize(JSON.parse(localStorage.getItem(SAVE)||'null'));}catch{}
let game=new Puzzle(profile.unlocked),brush:Piece|'erase'='straight',rotation=game.level===0?1:0,selected:string|null=null,resultShown=false,dialogResume=false,toastTimer=0;
const layouts=new Map<number,Map<string,Tile>>();const sound=new Sound();try{sound.enabled=localStorage.getItem('marble-parade-sound')!=='off';}catch{}
const icons:Record<Piece,string>={straight:'<path d="M20 6V42M28 6V42"/>',bend:'<path d="M20 6V15Q20 28 34 28H42M28 6V15Q28 20 34 20H42"/>',spring:'<path d="M15 31L33 26L15 21L33 16L15 11M13 34H35M17 8H31"/><path d="M24 40V44"/>',magnet:'<path d="M13 13V27a11 11 0 0022 0V13" stroke-width="8"/><path d="M13 9V16M35 9V16" stroke="#e99986" stroke-width="8"/>',seesaw:'<path d="M7 23L41 17M24 25L17 37H31Z"/><circle cx="10" cy="15" r="4" fill="#ed9580" stroke="none"/><circle cx="38" cy="9" r="4" fill="#81b9ca" stroke="none"/>'};
function icon(k:Piece,rot=0){return `<svg viewBox="0 0 48 48" aria-hidden="true" style="transform:rotate(${rot*90}deg)"><g fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round">${icons[k]}</g></svg>`;}
$('#app').innerHTML=`<main class="app-shell"><header><a class="brand" href="#" aria-label="Marble Parade home"><span class="brand-mark"><i></i><i></i><i></i></span><span>marble<br><b>parade.</b></span></a><div class="header-note">SMALL PIECES.<br>HAPPY ACCIDENTS.</div><nav aria-label="Game menu"><button id="map" class="nav-button">▦ <span>Tables</span></button><button id="style" class="nav-button">✿ <span>Studio</span></button><button id="help" class="round-button" aria-label="How to play">?</button><button id="sound" class="round-button" aria-label="Toggle sound">♫</button></nav></header><section class="intro"><div><div class="eyebrow"><span class="status-dot"></span><span id="chapter"></span></div><h1>Ready, set, <em>roll.</em></h1><p id="brief"></p></div><div class="score-card"><span class="small-label">HAPPY LANDINGS</span><div><b id="collected">0</b><span id="total">/ 1</span><i class="mini-marble"></i></div><small id="piece-count"></small></div></section><section class="play-area" aria-label="Puzzle board"><div class="board-meta"><span id="level-name"></span><button id="hint">✧ A little hint</button></div><div id="world"></div><div class="board-caption"><span id="state-label">BUILD YOUR LITTLE JOURNEY</span><span id="best-stars"></span></div></section><section class="workbench" aria-label="Track pieces"><div class="bench-top"><span class="small-label">YOUR LITTLE TOOLBOX</span><span id="tool-tip">Choose a piece, then tap a square.</span></div><div class="tools-row"><div id="inventory"></div><button id="roll" class="roll-button"><span>▶</span> Roll marbles</button></div><div class="bench-bottom"><div class="edit-tools"><button id="rotate" title="Rotate (R)">↻ <span>Rotate</span><b id="direction">→</b></button><button id="erase" title="Erase a piece">⌫ <span>Erase</span></button><button id="undo" title="Undo">↶ <span>Undo</span></button><button id="clear">Clear</button></div><button id="retry">↺ Reset run</button><span class="keyboard-note">SPACE to roll · R to rotate</span></div></section><footer><span>MAKE A PATH. MAKE A LITTLE MAGIC.</span><span id="career"></span></footer></main><div id="toast" role="status" aria-live="polite"></div><dialog id="dialog"><button class="modal-close" aria-label="Close dialog">×</button><div id="modal-body"></div></dialog>`;
const world=new MarbleWorld($('#world'),profile);const dialog=$<HTMLDialogElement>('#dialog');
function save(){try{localStorage.setItem(SAVE,JSON.stringify(profile));}catch{}}
function toast(text:string){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=window.setTimeout(()=>$('#toast').classList.remove('show'),4200);}
function rememberLayout(){layouts.set(game.level,new Map([...game.board].map(([k,t])=>[k,{...t}])));}
function loadLevel(n:number){rememberLayout();game=new Puzzle(n);if(layouts.has(n))game.board=new Map([...layouts.get(n)!].map(([k,t])=>[k,{...t}]));brush=Object.keys(game.config.stock)[0] as Piece;rotation=n===0?1:0;selected=null;resultShown=false;world.reset();dialogResume=false;if(dialog.open)dialog.close();update(true);toast(game.config.lesson);}
function openModal(html:string){dialogResume=game.phase==='running';if(dialogResume)game.pause();$('#modal-body').innerHTML=html;dialog.showModal();update();}
function closeModal(){dialog.close();if(dialogResume&&game.phase==='paused')game.start();dialogResume=false;update();}
$('.modal-close').onclick=closeModal;dialog.addEventListener('cancel',e=>{e.preventDefault();closeModal();});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
function showMap(){openModal(`<span class="eyebrow">NINE LITTLE ADVENTURES</span><h2>Pick your table.</h2><p class="modal-intro">New pieces, new possibilities. Complete a table to open the next.</p><div class="level-grid">${LEVELS.map((l,i)=>`<button class="level-card ${i===game.level?'current':''}" data-level="${i}" ${i>profile.unlocked?'disabled':''}><span class="level-number">${i>profile.unlocked?'⌑':String(i+1).padStart(2,'0')}</span><strong>${l.name}</strong><span class="level-stars">${i>profile.unlocked?'LOCKED':profile.stars[i]?'★'.repeat(profile.stars[i])+'☆'.repeat(3-profile.stars[i]):i===game.level?'ON YOUR TABLE':'READY TO ROLL'}</span></button>`).join('')}</div>`);document.querySelectorAll<HTMLButtonElement>('[data-level]').forEach(b=>b.onclick=()=>loadLevel(Number(b.dataset.level)));}
function showStudio(){const total=profile.stars.reduce((a,b)=>a+b,0);openModal(`<span class="eyebrow">MAKE IT YOURS</span><h2>A little color.</h2><p class="modal-intro">${total} stars collected. Your new looks never change the marble colors you need to match.</p><h3>Table finishes</h3><div class="studio-grid">${['Warm oak','Lilac daydream','Ocean breeze'].map((name,i)=>`<button class="style-card ${profile.theme===i?'chosen':''}" data-theme="${i}" ${profile.unlocked<i*3?'disabled':''}><span class="swatch theme-${i}"></span><strong>${name}</strong><small>${profile.unlocked<i*3?`Finish table ${i*3}`:profile.theme===i?'Selected':'Unlocked'}</small></button>`).join('')}</div><h3>Marble finishes</h3><div class="studio-grid">${['The originals','Ribbon candy','Confetti dots'].map((name,i)=>`<button class="style-card ${profile.skin===i?'chosen':''}" data-skin="${i}" ${total<[0,6,15][i]?'disabled':''}><span class="swatch ball-${i}"></span><strong>${name}</strong><small>${total<[0,6,15][i]?`${[0,6,15][i]} stars needed`:profile.skin===i?'Selected':'Unlocked'}</small></button>`).join('')}</div>`);document.querySelectorAll<HTMLButtonElement>('[data-theme]').forEach(b=>b.onclick=()=>{profile.theme=Number(b.dataset.theme);save();const resume=dialogResume;dialog.close();showStudio();dialogResume=resume;});document.querySelectorAll<HTMLButtonElement>('[data-skin]').forEach(b=>b.onclick=()=>{profile.skin=Number(b.dataset.skin);save();const resume=dialogResume;dialog.close();showStudio();dialogResume=resume;});}
function showHelp(){openModal(`<span class="eyebrow">A SMALL GUIDE TO BIG LITTLE IDEAS</span><h2>Follow the happy path.</h2><p class="modal-intro">Guide every marble from its START to the cup of the same color. Rails keep the marbles on your planned route.</p><ol class="help-steps"><li><b>Pick & place.</b> Choose a piece below, then tap an empty square. You have a limited supply.</li><li><b>Turn it around.</b> Tap the same piece again to rotate. Use Rotate or R before placing to change its direction.</li><li><b>Let them roll.</b> Press Roll. Pause to think, or Reset run to edit. Your layout stays on the table.</li></ol><div class="help-pieces">${(Object.keys(PIECES) as Piece[]).map(k=>`<div>${icon(k)}<p><b>${PIECES[k].name}</b><br>${PIECES[k].hint}</p></div>`).join('')}</div><p class="help-note">A switch opens its matching gate for the whole run. A waiting marble moves again when the gate opens. Pieces marked 1 and 2 on a seesaw show its alternating exits.</p><div class="star-guide"><b>Collect three stars</b><span>★ Deliver every marble</span><span>★ Stay within the piece target</span><span>★ Meet the target without hints</span></div>`);}
$('#map').onclick=showMap;$('#style').onclick=showStudio;$('#help').onclick=showHelp;$('.brand').onclick=e=>{e.preventDefault();showMap();};
$('#sound').onclick=()=>{sound.unlock();sound.enabled=!sound.enabled;try{localStorage.setItem('marble-parade-sound',sound.enabled?'on':'off');}catch{}update();};
function choose(k:Piece|'erase'){brush=k;selected=null;world.hintCell=null;update(true);}
function rotate(){if(game.phase==='running'){toast('Pause the marbles before changing your layout.');return;}if(selected){const [x,z]=selected.split(',').map(Number);if(game.rotate(x,z)){rotation=game.board.get(selected)!.rot;resultShown=false;}}else rotation=(rotation+1)%4;update(true);}
$('#rotate').onclick=rotate;$('#erase').onclick=()=>choose(brush==='erase'?'straight':'erase');
$('#undo').onclick=()=>{if(game.undo()){selected=null;world.hintCell=null;resultShown=false;update(true);}};
$('#clear').onclick=()=>{if(game.used&&game.clear()){selected=null;world.hintCell=null;resultShown=false;update(true);toast('A fresh canvas. All your pieces are back.');}};
function retry(){game.retry();resultShown=false;selected=null;world.hintCell=null;update(true);}
$('#retry').onclick=retry;
function roll(){sound.unlock();world.hintCell=null;selected=null;if(game.phase==='running')game.pause();else if(game.phase==='won'||game.phase==='failed'){retry();game.start();}else game.start();update(true);}
$('#roll').onclick=roll;
$('#hint').onclick=()=>{if(game.phase==='running'){toast('Pause or reset the run to ask for a hint.');return;}const h=game.hint();if('x'in h)world.hintCell=`${h.x},${h.z}`;toast(h.text);update();};
let pointerStart={x:0,y:0};const canvas=world.renderer.domElement;canvas.addEventListener('pointerdown',e=>{pointerStart={x:e.clientX,y:e.clientY};});canvas.addEventListener('pointermove',e=>{world.hoverCell=world.pick(e.clientX,e.clientY);});canvas.addEventListener('pointerleave',()=>world.hoverCell=null);canvas.addEventListener('pointerup',e=>{if(Math.hypot(e.clientX-pointerStart.x,e.clientY-pointerStart.y)>12)return;const cell=world.pick(e.clientX,e.clientY);if(!cell)return;sound.unlock();if(game.phase==='running'){toast('Pause or reset the run to change a piece.');return;}world.hintCell=null;const [x,z]=cell.split(',').map(Number),t=game.board.get(cell);if(t?.fixed){const label=t.kind==='cup'?`The ${t.color} cup. Bring the matching marble here.`:t.kind==='source'?'The start. Follow its arrow toward the matching cup.':t.kind==='hole'?'A gap in the table. Jump across it with a spring.':t.kind==='switch'?`The ${t.key} switch opens the matching gate.`:`The ${t.key} gate waits for its matching switch.`;toast(label);return;}let changed=false;if(brush==='erase'){changed=game.erase(x,z);selected=null;}else if(t?.kind===brush){changed=game.rotate(x,z);selected=cell;rotation=game.board.get(cell)!.rot;}else{changed=game.place(x,z,brush,rotation);if(changed)selected=cell;else toast(`No ${PIECES[brush].name.toLowerCase()} pieces left. Move one or choose another piece.`);}if(changed)resultShown=false;update(true);});
window.addEventListener('keydown',e=>{if(dialog.open||e.target instanceof HTMLInputElement)return;if(e.code==='Space'){e.preventDefault();roll();}if(e.key.toLowerCase()==='r'){e.preventDefault();rotate();}if(e.key.toLowerCase()==='z'&&(e.metaKey||e.ctrlKey)){e.preventDefault();$('#undo').click();}if(e.key==='Backspace'&&selected){e.preventDefault();const[x,z]=selected.split(',').map(Number);game.erase(x,z);selected=null;update(true);}const n=Number(e.key)-1,k=(Object.keys(PIECES) as Piece[])[n];if(k&&game.config.stock[k])choose(k);});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&game.phase==='running'){game.pause();update();}});
let uiSignature='';function update(force=false){const signature=JSON.stringify([game.level,game.phase,game.used,game.collected,game.revision,brush,rotation,selected,sound.enabled,profile.stars]);if(!force&&signature===uiSignature)return;uiSignature=signature;
 $('#chapter').textContent=`TABLE ${String(game.level+1).padStart(2,'0')} / 09 · ${game.config.subtitle}`;$('#brief').textContent=game.config.brief;$('#level-name').textContent=`${String(game.level+1).padStart(2,'0')} — ${game.config.name}`;$('#collected').textContent=String(game.collected);$('#total').textContent=`/ ${game.total}`;$('#piece-count').textContent=`${game.used} pieces · target ${game.config.par}`;$('#state-label').textContent=game.phase==='build'?selected?`${cellName(...selected.split(',').map(Number) as [number,number])} SELECTED · TAP AGAIN TO ROTATE`:'BUILD YOUR LITTLE JOURNEY':game.phase==='running'?'A LITTLE MAGIC IN MOTION':game.phase==='paused'?'PAUSED · EDIT A PIECE OR KEEP ROLLING':game.phase==='won'?'EVERY MARBLE, RIGHT AT HOME':'A LITTLE TWEAK. ANOTHER TRY.';$('#best-stars').textContent=profile.stars[game.level]?'★'.repeat(profile.stars[game.level])+'☆'.repeat(3-profile.stars[game.level]):`TARGET: ${game.config.par} PIECES`;
 $('#inventory').innerHTML=(Object.keys(PIECES) as Piece[]).filter(k=>game.config.stock[k]).map(k=>`<button class="piece-tool ${brush===k?'active':''} ${game.remaining(k)===0?'empty':''}" data-piece="${k}" aria-pressed="${brush===k}" title="${PIECES[k].hint}">${icon(k,brush===k?rotation:0)}<span>${PIECES[k].name}</span><b>${game.remaining(k)}</b></button>`).join('');document.querySelectorAll<HTMLButtonElement>('[data-piece]').forEach(b=>b.onclick=()=>choose(b.dataset.piece as Piece));$('#direction').textContent=['↑','→','↓','←'][rotation];$('#tool-tip').textContent=brush==='erase'?'Tap a placed piece to return it to your toolbox.':PIECES[brush].hint;$('#erase').classList.toggle('active',brush==='erase');$('#roll').innerHTML=game.phase==='running'?'<span>Ⅱ</span> Pause':game.phase==='paused'?'<span>▶</span> Keep rolling':'<span>▶</span> Roll marbles';$('#roll').classList.toggle('running',game.phase==='running');$<HTMLButtonElement>('#undo').disabled=!game.history.length||game.phase==='running';$<HTMLButtonElement>('#clear').disabled=!game.used||game.phase==='running';$<HTMLButtonElement>('#rotate').disabled=game.phase==='running'||brush==='erase';$<HTMLButtonElement>('#retry').disabled=game.phase==='build';$('#sound').textContent=sound.enabled?'♫':'♩';$('#sound').setAttribute('aria-label',sound.enabled?'Mute sound':'Enable sound');$('#sound').classList.toggle('muted',!sound.enabled);$('#career').textContent=`${profile.stars.reduce((a,b)=>a+b,0)} / 27 STARS`;
}
function result(){if(resultShown)return;resultShown=true;if(game.phase==='won'){profile.stars[game.level]=Math.max(profile.stars[game.level],game.stars);profile.unlocked=Math.max(profile.unlocked,Math.min(8,game.level+1));save();const final=game.level===8;openModal(`<div class="result-content"><span class="eyebrow">${final?'THE WHOLE PARADE IS HOME':'A PERFECT LITTLE LANDING'}</span><div class="big-stars">${'★'.repeat(game.stars)}<span>${'★'.repeat(3-game.stars)}</span></div><h2>${final?'What a happy parade.':'Right where they belong.'}</h2><p>${game.total} ${game.total===1?'marble':'marbles'} home · ${game.used} pieces · ${game.time.toFixed(1)} seconds</p><p class="result-note">${game.stars===3?'A beautiful route. You earned all three stars.':game.used>game.config.par?`Try ${game.config.par} pieces or fewer for another star.`:'Solve it again without a hint for the final star.'}</p>${[2,5].includes(game.level)?'<p class="unlock-note">✿ A new table finish is waiting in your Studio.</p>':''}<button class="primary" id="next">${final?'Explore your tables':'Next little adventure →'}</button><button class="text-button" id="again">Tinker with this table</button></div>`);$('#next').onclick=()=>{dialog.close();if(final)showMap();else loadLevel(game.level+1);};$('#again').onclick=()=>{dialog.close();game.hints=0;retry();};}else{openModal(`<div class="result-content"><span class="eyebrow">HAPPY ACCIDENTS HAPPEN</span><div class="oops-marble"></div><h2>A little adjustment.</h2><p>${game.message}</p><p class="result-note">Your layout is still here. Turn a piece, connect a gap, and give it another go.</p><button class="primary" id="edit-layout">Back to the workbench</button><button class="text-button" id="failure-hint">Show me a little hint</button></div>`);$('#edit-layout').onclick=()=>{dialog.close();retry();};$('#failure-hint').onclick=()=>{dialog.close();retry();$('#hint').click();};}update(true);}
let last=performance.now(),accumulator=0,resultDelay=-1;
function frame(now:number){const dt=Math.min((now-last)/1000,.05);last=now;accumulator+=dt;while(accumulator>=1/60){game.tick(1/60);accumulator-=1/60;}for(const event of game.events.splice(0)){world.event(event);sound.play(event);if(event.type==='win'||event.type==='fail')resultDelay=.65;}if(resultDelay>=0){resultDelay-=dt;if(resultDelay<0&&(game.phase==='won'||game.phase==='failed'))result();}world.update(game,dt,game.phase==='running'?accumulator*60:1);update();requestAnimationFrame(frame);}
(window as unknown as {render_game_to_text:()=>string}).render_game_to_text=()=>JSON.stringify({...game.snapshot(),selected,brush,rotation,remaining:Object.fromEntries(Object.keys(game.config.stock).map(k=>[k,game.remaining(k as Piece)])),board:[...game.board].map(([cell,t])=>({cell,...t})),profile});
update(true);requestAnimationFrame(frame);
