import * as T from 'three';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {COLORS,dirs,key,type Tile,type Color} from './levels';import {type Puzzle,type Event,type Profile} from './simulation';
const INK=0x42546a,CREAM=0xfff0cf,WOOD=0xc4a27a,STEP=1.08,BASE=.31;
const palettes=[{bg:0xf3eddd,wood:0xc9a681,pad:0xf5e9ca,rim:0x86bfb1},{bg:0xeae9ee,wood:0xb9a4bd,pad:0xf1e6dc,rim:0xaf9ecb},{bg:0xe4eef0,wood:0xb2c5c9,pad:0xf0e7ce,rim:0x72b3ca}];
const accents=[0xeaa28b,0x8dbbc6,0xe6c465,0x9dc6a8,0xb99bcf,0xe5a5bb];
interface FX{mesh:T.Mesh;v:T.Vector3;life:number;max:number}
export class MarbleWorld{
 renderer:T.WebGLRenderer;scene=new T.Scene();camera=new T.OrthographicCamera();table=new T.Group();pieces=new T.Group();ballRoot=new T.Group();pieceMap=new Map<string,T.Group>();ballMap=new Map<number,T.Group>();mats=new Map<number,T.MeshStandardMaterial>();ray=new T.Raycaster();mouse=new T.Vector2();hover=new T.LineLoop();pickPlanes:T.Mesh[]=[];fx:FX[]=[];time=0;stage=-1;revision=-1;theme=-1;skin=-1;hoverCell:string|null=null;hintCell:string|null=null;birth=new Map<string,number>();profile:Profile;current!:Puzzle;reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 constructor(public host:HTMLElement,profile:Profile){this.profile=profile;this.renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.05;host.appendChild(this.renderer.domElement);this.renderer.domElement.setAttribute('aria-label','A six by six marble table. Tap empty squares to place tracks.');this.scene.add(new T.HemisphereLight(0xfff6e3,0x9bb4b4,1.8));const sun=new T.DirectionalLight(0xfff2d7,2);sun.position.set(-5,13,7);sun.castShadow=true;const resolution=innerWidth<700?1024:2048;sun.shadow.mapSize.set(resolution,resolution);Object.assign(sun.shadow.camera,{left:-8,right:8,top:8,bottom:-8,near:.5,far:30});sun.shadow.normalBias=.04;sun.shadow.bias=-.0002;this.scene.add(sun,this.table,this.pieces,this.ballRoot);this.hover=new T.LineLoop(new T.BufferGeometry().setFromPoints([new T.Vector3(-.5,0,-.5),new T.Vector3(.5,0,-.5),new T.Vector3(.5,0,.5),new T.Vector3(-.5,0,.5)]),new T.LineBasicMaterial({color:0xd8865c}));this.hover.visible=false;this.scene.add(this.hover);this.resize();new ResizeObserver(()=>this.resize()).observe(host);}
 mat(color:number){if(!this.mats.has(color))this.mats.set(color,new T.MeshStandardMaterial({color,roughness:.78}));return this.mats.get(color)!;}
 mesh(geometry:T.BufferGeometry,color:number,parent:T.Object3D){const m=new T.Mesh(geometry,this.mat(color));m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 box(w:number,h:number,d:number,color:number,parent:T.Object3D,x=0,y=0,z=0,r=.04){const m=this.mesh(new RoundedBoxGeometry(w,h,d,1,r),color,parent);m.position.set(x,y,z);return m;}
 cyl(r:number,h:number,color:number,parent:T.Object3D,x=0,y=0,z=0){const m=this.mesh(new T.CylinderGeometry(r,r,h,24),color,parent);m.position.set(x,y,z);return m;}
 sphere(r:number,color:number,parent:T.Object3D,x=0,y=0,z=0){const m=this.mesh(new T.SphereGeometry(r,20,12),color,parent);m.position.set(x,y,z);return m;}
 label(text:string,w:number,h:number,color='#766c60',bg?:string){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=128;const c=canvas.getContext('2d')!;if(bg){c.fillStyle=bg;c.fillRect(0,0,512,128);}c.fillStyle=color;c.font='900 63px Arial';c.textAlign='center';c.textBaseline='middle';c.fillText(text,256,66);const tex=new T.CanvasTexture(canvas);tex.colorSpace=T.SRGBColorSpace;const mesh=new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false,side:T.DoubleSide}));return mesh;}
 flatText(text:string,w:number,h:number,parent:T.Object3D,x:number,y:number,z:number,color?:string){const m=this.label(text,w,h,color);m.rotation.x=-Math.PI/2;m.position.set(x,y,z);parent.add(m);return m;}
 arrow(g:T.Object3D,x=0,y=.36,z=-.28,color=0xd3955f,size=.12){const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute([0,0,-size,-size*.7,0,size*.4,size*.7,0,size*.4],3));geo.computeVertexNormals();const m=this.mesh(geo,color,g);m.position.set(x,y,z);m.material=this.mat(color);(m.material as T.Material).side=T.DoubleSide;return m;}
 lane(g:T.Group,a:number,b:number){const start=new T.Vector3(dirs[a].x*.54,0,dirs[a].z*.54),end=new T.Vector3(dirs[b].x*.54,0,dirs[b].z*.54),curve=new T.QuadraticBezierCurve3(start,new T.Vector3(),end);const bed=this.mesh(new T.TubeGeometry(curve,24,.175,8,false),0xddbd8e,g);bed.scale.y=.12;bed.position.y=BASE-.012;for(const side of [-1,1]){const pts=[];for(let i=0;i<=24;i++){const t=i/24,p=curve.getPoint(t),v=curve.getTangent(t);pts.push(new T.Vector3(p.x+v.z*.195*side,BASE+.048,p.z-v.x*.195*side));}this.mesh(new T.TubeGeometry(new T.CatmullRomCurve3(pts),24,.034,6,false),CREAM,g);}for(const d of [a,b])this.cyl(.035,.013,0xbca378,g,dirs[d].x*.45,BASE-.005,dirs[d].z*.45);}
 tile(t:Tile){const g=new T.Group();g.rotation.y=-t.rot*Math.PI/2;if(!t.fixed){const accent={straight:0x81b8c8,bend:0xe2a18c,spring:0xe7c164,magnet:0xb298c7,seesaw:0x84b89f}[t.kind as 'straight'];if(accent)this.cyl(.05,.012,accent,g,-.38,.332,-.38);}const fixedColor=t.key==='mint'?0x71b7a2:0xefb45b;
  if(t.kind==='straight'||t.kind==='gate'||t.kind==='switch'&&t.shape!=='bend')this.lane(g,0,2);
  if(t.kind==='bend'||t.kind==='switch'&&t.shape==='bend')this.lane(g,0,1);
  if(t.kind==='spring'){this.lane(g,2,0);const coil=new T.Group();g.add(coil);coil.position.y=BASE;const pts=[];for(let i=0;i<=80;i++){const a=i/80*Math.PI*10;pts.push(new T.Vector3(Math.cos(a)*.12,i/80*.2,Math.sin(a)*.12));}this.mesh(new T.TubeGeometry(new T.CatmullRomCurve3(pts),80,.018,6,false),0xdf9382,coil);this.cyl(.18,.065,0xf3cb6d,coil,0,.23,0);this.arrow(g,0,BASE+.02,-.4,0xd89d43,.12);g.userData.coil=coil;}
  if(t.kind==='magnet'){for(const d of [1,2,3])this.lane(g,d,0);const magnet=new T.Group();g.add(magnet);const tor=this.mesh(new T.TorusGeometry(.18,.065,8,18,Math.PI),0xb399cd,magnet);tor.rotation.x=-Math.PI/2;tor.position.set(.26,.56,.18);for(const x of [.08,.44])this.box(.12,.08,.13,0xefb3a4,magnet,x,.56,.29);this.arrow(g,0,.38,-.34,0x9d83bd,.13);g.userData.magnet=magnet;}
  if(t.kind==='seesaw'){this.lane(g,2,1);this.lane(g,2,3);const rocker=new T.Group();rocker.position.y=BASE+.05;g.add(rocker);this.box(.62,.045,.18,0x83b9ab,rocker,0,0,.05,.03);const fulcrum=this.mesh(new T.ConeGeometry(.13,.15,3),0xd6ad77,g);fulcrum.position.set(0,.32,.05);this.arrow(g,0,.36,.37,0x568b80,.1);this.cyl(.08,.025,COLORS.coral,g,.38,.36,0);this.cyl(.08,.025,COLORS.blue,g,-.38,.36,0);this.flatText('1',.09,.08,g,.38,.38,0,'#fff6df');this.flatText('2',.09,.08,g,-.38,.38,0,'#fff6df');g.userData.rocker=rocker;}
  if(t.kind==='switch'){const button=new T.Group();button.position.set(-.31,BASE+.045,-.3);g.add(button);this.cyl(.135,.075,fixedColor,button);this.cyl(.055,.006,CREAM,button,0,.041,0);g.userData.button=button;}
  if(t.kind==='gate'){for(const x of [-.31,.31])this.cyl(.045,.38,INK,g,x,.45,0);const door=new T.Group();door.position.set(-.31,.54,0);g.add(door);this.box(.62,.11,.075,fixedColor,door,.31,0,0,.02);for(let i=0;i<3;i++)this.box(.045,.115,.082,CREAM,door,.12+i*.16,0,0,.006).rotation.z=.25;g.userData.door=door;}
  if(t.kind==='source'){this.cyl(.3,.12,0x86bba9,g,0,.28,0);this.cyl(.23,.13,0x578f82,g,0,.32,0);this.lane(g,2,0);this.arrow(g,0,.35,-.39,0x4e8c80,.13);const flag=this.label('START',.61,.17,'#5c8372','#fff4d5');flag.position.set(0,.85,.16);flag.quaternion.setFromEuler(new T.Euler(-Math.PI/3,0,0));flag.quaternion.premultiply(new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),t.rot*Math.PI/2));g.add(flag);for(let i=0;i<t.colors!.length;i++)this.sphere(.09,COLORS[t.colors![i]],g,(i-(t.colors!.length-1)/2)*.2,.58,.13);}
  if(t.kind==='cup'){this.cyl(.29,.03,0x405b66,g,0,.265,0);const rim=this.mesh(new T.TorusGeometry(.305,.064,10,28),COLORS[t.color!],g);rim.rotation.x=-Math.PI/2;rim.position.y=.31;this.cyl(.35,.045,COLORS[t.color!],g,0,.24,0);this.cyl(.255,.032,0x405b66,g,0,.329,0);const flag=new T.Group();g.add(flag);flag.position.set(.34,.48,.33);this.cyl(.015,.37,WOOD,flag,0,.08,0);const label=this.label('★',.29,.25,'#fff4d3','#'+COLORS[t.color!].toString(16));label.position.y=.25;flag.add(label);g.userData.flag=flag;}
  return g;
 }
 rebuild(game:Puzzle){this.stage=game.level;this.theme=this.profile.theme;this.revision=-1;this.clear(this.table);this.pickPlanes=[];const p=palettes[this.theme];this.renderer.setClearColor(p.bg);const floor=this.mesh(new T.PlaneGeometry(150,150),p.bg,this.table);floor.rotation.x=-Math.PI/2;floor.position.y=-.69;floor.castShadow=false;(floor as T.Mesh<T.BufferGeometry,T.Material>).material=new T.ShadowMaterial({color:0x69615c,opacity:.16});document.body.style.background=`#${p.bg.toString(16)}`;
  this.box(7.4,.4,7.4,p.wood,this.table,0,-.015,0,.2);this.box(7.05,.08,7.05,p.rim,this.table,0,.22,0,.15);this.box(6.75,.045,6.75,p.pad,this.table,0,.267,0,.1);
  for(const x of [-2.9,2.9])for(const z of [-2.9,2.9])this.cyl(.25,.65,accents[game.config.theme],this.table,x,-.35,z);
  for(let z=0;z<6;z++)for(let x=0;x<6;x++){const tile=game.board.get(key(x,z)),cx=(x-2.5)*STEP,cz=(z-2.5)*STEP;const pad=this.box(1.015,.055,1.015,tile?.kind==='hole'?0x667887:tile?.fixed?0xe0dfc6:p.pad,this.table,cx,.29,cz,.075);pad.userData.cell=key(x,z);this.pickPlanes.push(pad);if(tile?.kind==='hole'){this.box(.8,.03,.8,0x40515d,this.table,cx,.325,cz,.08);}else{this.cyl(.025,.008,0xc8b799,this.table,cx,.322,cz);}}
  for(let i=0;i<6;i++){this.flatText('ABCDEF'[i],.21,.19,this.table,(i-2.5)*STEP,.285,3.43);this.flatText(String(i+1),.17,.17,this.table,-3.43,.285,(i-2.5)*STEP);}
  const badge=this.label('MARBLE PARADE',2.6,.28,'#7d6856');badge.position.set(0,-.08,3.72);this.table.add(badge);
  this.box(1.25,.16,1.25,accents[game.config.theme],this.table,-4.6,-.49,1.6,.15);for(let i=0;i<5;i++)this.sphere(.17,[COLORS.coral,COLORS.blue,COLORS.gold][i%3],this.table,-4.8+(i%3)*.22,-.21,1.4+Math.floor(i/3)*.28);
  const pot=this.cyl(.35,.55,0xe9a794,this.table,4.5,-.39,-2.1);this.cyl(.36,.1,CREAM,this.table,4.5,-.12,-2.1);for(let i=0;i<5;i++){const leaf=this.sphere(.24,[0x7eae8c,0xa5c297][i%2],this.table,4.5+Math.sin(i*2)*.18,.2+i*.09,-2.1+Math.cos(i*2)*.13);leaf.scale.set(.5,1.3,.4);leaf.rotation.z=Math.sin(i*2)*.4;}
  for(let i=0;i<3;i++)this.box(.62,.36,.62,[0x98bdd0,0xeab799,0xb29dc6][i],this.table,4.4+(i%2)*.25,-.42+i*.36,2.3,.07).rotation.y=i*.32;
 }
 rebuildPieces(game:Puzzle){this.clear(this.pieces);this.pieceMap.clear();for(const[k,t]of game.board){if(t.kind==='hole')continue;const[x,z]=k.split(',').map(Number),g=this.tile(t);g.position.set((x-2.5)*STEP,0,(z-2.5)*STEP);this.pieces.add(g);this.pieceMap.set(k,g);}this.revision=game.revision;}
 ball(color:Color){const g=new T.Group(),mat=new T.MeshStandardMaterial({color:COLORS[color],roughness:.18,metalness:.16});const body=new T.Mesh(new T.SphereGeometry(.162,24,16),mat);body.userData.uniqueMaterial=true;body.castShadow=true;g.add(body);if(this.profile.skin===1){const ring=this.mesh(new T.TorusGeometry(.159,.012,6,32),CREAM,g);ring.rotation.x=.5;ring.rotation.y=.4;}if(this.profile.skin===2)for(let i=0;i<8;i++){const a=i*2.4;this.sphere(.021,CREAM,g,Math.sin(a)*.145,Math.cos(i*.8)*.085,Math.cos(a)*.145);}return g;}
 pick(x:number,y:number){const r=this.renderer.domElement.getBoundingClientRect();this.mouse.set((x-r.left)/r.width*2-1,-(y-r.top)/r.height*2+1);this.ray.setFromCamera(this.mouse,this.camera);return this.ray.intersectObjects(this.pickPlanes,false)[0]?.object.userData.cell??null;}
 resize(){const w=this.host.clientWidth,h=this.host.clientHeight,aspect=w/h,span=w<700?Math.max(7.5,8.7/aspect):aspect<1.3?8.6:7.7;this.camera.left=-span*aspect/2;this.camera.right=span*aspect/2;this.camera.top=span/2;this.camera.bottom=-span/2;this.camera.near=.5;this.camera.far=60;this.camera.position.set(0,13,8);this.camera.lookAt(0,.08,0);this.camera.updateProjectionMatrix();this.renderer.setSize(w,h);}
 burst(cell:string,color:number,count=12){const[x,z]=cell.split(',').map(Number);for(let i=0;i<count&&this.fx.length<100;i++){const m=this.mesh(new T.BoxGeometry(.06,.06,.06),color,this.scene);m.position.set((x-2.5)*STEP,.6,(z-2.5)*STEP);m.castShadow=false;m.receiveShadow=false;const life=.5+Math.random()*.5;this.fx.push({mesh:m,v:new T.Vector3((Math.random()-.5)*1.5,1+Math.random()*1.5,(Math.random()-.5)*1.5),life,max:life});}}
 event(e:Event){if(e.type==='place'||e.type==='rotate')this.birth.set(e.cell!,this.time);if(e.type==='catch')this.burst(e.cell!,COLORS[e.color!],12);if(e.type==='win')for(const c of ['coral','blue','gold'] as Color[])this.burst('2,2',COLORS[c],12);}
 update(game:Puzzle,dt:number,alpha=1){this.current=game;this.time+=dt;if(this.stage!==game.level||this.theme!==this.profile.theme)this.rebuild(game);if(this.revision!==game.revision)this.rebuildPieces(game);if(this.skin!==this.profile.skin){this.clear(this.ballRoot);this.ballMap.clear();this.skin=this.profile.skin;}
  for(const[k,g]of this.pieceMap){const age=this.time-(this.birth.get(k)??-100);g.position.y=!this.reduced&&age<.28?Math.sin(age/.28*Math.PI)*.12:0;const tile=game.board.get(k)!;const t=game.time-(game.pulses.get(k)??-100);
   if(g.userData.coil)g.userData.coil.scale.y=t<.3?.4+.6*Math.min(1,t/.3):1;
   if(g.userData.magnet)g.userData.magnet.position.y=t<.45?Math.sin(t/.45*Math.PI)*.07:0;
   if(g.userData.rocker){const desired=(game.flips.get(k)||0)%2?-.13:.13;g.userData.rocker.rotation.z=T.MathUtils.lerp(g.userData.rocker.rotation.z,desired,1-Math.exp(-dt*12));}
   if(g.userData.button)g.userData.button.position.y=BASE+.045-(game.gates.has(tile.key!)?.035:0);
   if(g.userData.door)g.userData.door.rotation.y=T.MathUtils.lerp(g.userData.door.rotation.y,game.gates.has(tile.key!)?-Math.PI/2:0,1-Math.exp(-dt*10));
   if(g.userData.flag)g.userData.flag.rotation.z=t<.5?Math.sin(t*16)*.12:0;
  }
  const ids=new Set(game.balls.map(b=>b.id));for(const[id,g]of this.ballMap)if(!ids.has(id)){this.ballRoot.remove(g);this.clear(g);this.ballMap.delete(id);}
  for(const b of game.balls){let g=this.ballMap.get(b.id);if(!g){g=this.ball(b.color);this.ballRoot.add(g);this.ballMap.set(b.id,g);}g.visible=!['scheduled','caught'].includes(b.state);const x=T.MathUtils.lerp(b.previous.x,b.position.x,alpha),y=T.MathUtils.lerp(b.previous.y,b.position.y,alpha),z=T.MathUtils.lerp(b.previous.z,b.position.z,alpha);const old=g.position.clone();g.position.set((x-2.5)*STEP,BASE+y,(z-2.5)*STEP);if(g.visible){g.rotation.z-=(g.position.x-old.x)/.162;g.rotation.x+=(g.position.z-old.z)/.162;}}
  const hover=this.hintCell||this.hoverCell;this.hover.visible=!!hover&&game.phase==='build';if(hover){const[x,z]=hover.split(',').map(Number);this.hover.position.set((x-2.5)*STEP,.365,(z-2.5)*STEP);}
  for(const fx of [...this.fx]){fx.life-=dt;fx.v.y-=dt*4;fx.mesh.position.addScaledVector(fx.v,dt);fx.mesh.rotation.x+=dt*3;fx.mesh.scale.setScalar(Math.max(0,fx.life/fx.max));if(fx.life<=0){this.scene.remove(fx.mesh);fx.mesh.geometry.dispose();this.fx.splice(this.fx.indexOf(fx),1);}}
  this.renderer.render(this.scene,this.camera);
 }
 clear(g:T.Group){g.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.Line){o.geometry.dispose();const m=o.material;if(m instanceof T.MeshBasicMaterial){m.map?.dispose();m.dispose();}else if(m instanceof T.ShadowMaterial||o.userData.uniqueMaterial){if(!Array.isArray(m))m.dispose();}}});g.clear();}
 reset(){this.stage=-1;this.revision=-1;this.birth.clear();this.hintCell=null;this.hoverCell=null;for(const f of this.fx){this.scene.remove(f.mesh);f.mesh.geometry.dispose();}this.fx=[];this.clear(this.ballRoot);this.ballMap.clear();}
}
